/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_presentacion;

import Capa_presentacion.nomina.*;
import javax.swing.WindowConstants;

/**
 *
 * @author HP
 */
public class Nomina extends javax.swing.JFrame {

    /**
     * Creates new form Nomina
     */
    public Nomina() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Motivo_BTN = new javax.swing.JButton();
        Empleado_BTN = new javax.swing.JButton();
        Detalle_BTN = new javax.swing.JButton();
        Valores_BTN = new javax.swing.JButton();
        Reporte_BTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setText("Nomina");

        Motivo_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Motivo_BTN.setText("Motivo de Ingreso");
        Motivo_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Motivo_BTNActionPerformed(evt);
            }
        });

        Empleado_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Empleado_BTN.setText("Detalles Empleado");
        Empleado_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Empleado_BTNActionPerformed(evt);
            }
        });

        Detalle_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Detalle_BTN.setText("Detalle Nomina");
        Detalle_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detalle_BTNActionPerformed(evt);
            }
        });

        Valores_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Valores_BTN.setText("Valores a Pagar");
        Valores_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Valores_BTNActionPerformed(evt);
            }
        });

        Reporte_BTN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Reporte_BTN.setText("Reporte");
        Reporte_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reporte_BTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(323, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(313, 313, 313))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Motivo_BTN)
                            .addGap(299, 299, 299)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Reporte_BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Valores_BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Detalle_BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Empleado_BTN, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(Motivo_BTN)
                .addGap(18, 18, 18)
                .addComponent(Empleado_BTN)
                .addGap(18, 18, 18)
                .addComponent(Detalle_BTN)
                .addGap(18, 18, 18)
                .addComponent(Valores_BTN)
                .addGap(18, 18, 18)
                .addComponent(Reporte_BTN)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Motivo_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Motivo_BTNActionPerformed
        // TODO add your handling code here:
        Motivo motivo = new Motivo();
        motivo.setVisible(true);
        
    }//GEN-LAST:event_Motivo_BTNActionPerformed

    private void Empleado_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Empleado_BTNActionPerformed
        // TODO add your handling code here:
        Empleado empleado = new Empleado();
        empleado.setVisible(true);
    }//GEN-LAST:event_Empleado_BTNActionPerformed

    private void Detalle_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detalle_BTNActionPerformed
        // TODO add your handling code here:
        Detalle_nomina detalle = new Detalle_nomina();
        detalle.setVisible(true);
    }//GEN-LAST:event_Detalle_BTNActionPerformed

    private void Valores_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Valores_BTNActionPerformed
        // TODO add your handling code here:
        Valores_pagar valores = new Valores_pagar();
        valores.setVisible(true);
    }//GEN-LAST:event_Valores_BTNActionPerformed

    private void Reporte_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reporte_BTNActionPerformed
        // TODO add your handling code here:
        Reporte reporte = new Reporte();
        reporte.setVisible(true);
    }//GEN-LAST:event_Reporte_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nomina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nomina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Detalle_BTN;
    private javax.swing.JButton Empleado_BTN;
    private javax.swing.JButton Motivo_BTN;
    private javax.swing.JButton Reporte_BTN;
    private javax.swing.JButton Valores_BTN;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
